### ISSUE TITLE
Download is not working

### ISSUE THREAD

**Issue by abelfn** [yausername/dvd#1]
when i select the download format it display toast message
Download queued. Check notification for progress and notification disappear after few seconds.  There is nothing in the downloads section. 
Plus returns unnecessary format with the correct format for some video sites .

**Comment by yausername** [comment]
Can you provide these info?
* Video link
* Android version (device model name also if possible)

**Comment by abelfn** [comment]
any website i tryed 

https://m.youtube.com/watch?v=XjnYJLrlfVQ

Android 8.1.0 oreo 
Samsung galaxy A2 Core
SM-A260G

**Comment by abelfn** [comment]
sorry i just accidentally clicked close issue button

**Comment by yausername** [comment]
@abelfn Please try with release https://github.com/yausername/dvd/releases/tag/0.0.2
Make sure you uninstall previous version before installing this.
