### ISSUE TITLE
Task counter in notification doesn't work

### ISSUE THREAD

**Issue by 0ddb0d** [yausername/dvd#13]
![Screenshot_20210202-135145_dvd](https://user-images.githubusercontent.com/45958107/106545732-0f1fb700-655e-11eb-856c-a18bf7ab2084.png)

Not working yet?

**Comment by yausername** [comment]
Thanks for reporting.
It's a known issue. Need to get the task number from youtube-dl.
Will be fixed sometime later.

**Comment by xibr** [comment]
See https://github.com/yausername/dvd/pull/46
