### ISSUE TITLE
Option: Use stream in/for media player

### ISSUE THREAD

**Issue by famo** [yausername/dvd#15]
In addition to downloading, it would be nice to have the option to stream the media file with the default media player or chosen one.

**Comment by Artim96** [comment]
Or at least being able to copy a link for that. That could be helpful

**Comment by xibr** [comment]
I will go with a share button from which you can copy the link or open it in any other player such as mpv android.

![20220207_213654](https://user-images.githubusercontent.com/20098154/152841757-b009334d-0d79-4038-89a1-adad32e5f0c3.jpg)
