### ISSUE TITLE
[Suggested App Features and Improvements]

### ISSUE THREAD

**Issue by Jpersh27** [yausername/dvd#17]
@yausername- I have several suggestions of new app features that would improve the apps functionality. 

1.) While downloading video links It would be nice to have a pause and resume the download feature.

2.) After the video file is Downloaded it would be nice to have the ability to Long Press on a downloaded file or even swipe left or right across the file name to clear it from the downloads list under the downloads tab. 

3.) Add the Ability to speed up Video downloads by splitting the file up into different parts similar to IDM+ which allows you to split the file up into 32 parts. 

• (These additional parts are created and queued and started when the other parts are finished)

4.) Show the estimated time (ETA) until the video file is completed/finished.

• Implement a progress bar notification showing the progress of the downloaded file. Ex: 30 seconds left or 40% Downloaded.

5.) Lastly Create an empty file to help accelerate the download progress. 

• All of these features above are examples of the many little things that the app IDM+ does right and correctly with it's in app download manager features. It would be nice to see these features get implemented into this app.

**Comment by Jpersh27** [comment]
@yausername Do you have any plans to view my request or anyone else's request in this repository? 

2.) Or is the development of this app done and no longer being supported?

• Last release/update for this app was almost 2 months ago back in January.

**Comment by yausername** [comment]
Hi, Thanks for your suggestions.
But I'm busy for the next few months with other things. I won't be able to find time for this.

If someone else pitches in I would be happy to review a PR or two.
