### ISSUE TITLE
Can't set location

### ISSUE THREAD

**Issue by CoreyVidal** [yausername/dvd#2]
I took a screen record. See it here:

https://imgur.com/a/qkJfuqx

I'm on Samsung Galaxy Note 10+, Android 10.

**Comment by yausername** [comment]
Hi,
Please try with [this](https://send.firefox.com/download/db0932633383c4e0/#EmQv9oTvOsdNLcIfahM4Qg) apk.
Make sure you uninstall the older version before installing this.

**Comment by CoreyVidal** [comment]
Yep, fixed.
