### ISSUE TITLE
Downloading Status 

### ISSUE THREAD

**Issue by testherokuvictim** [yausername/dvd#25]
I love this app.

I find Difficult on knowing downloaded size of file and want to download yet so please add status fir downloading.

**Comment by PigDan20** [comment]
+1

**Comment by morocoeltopo** [comment]
+1

**Comment by xibr** [comment]
What about display 
`[download]  10.0% of 9.69MiB at 585.50KiB/s ETA 00:15` 
instead of `Task ?/n (ETA ... seconds)`

**Comment by yausername** [comment]
> What about display
> `[download] 10.0% of 9.69MiB at 585.50KiB/s ETA 00:15`
> instead of `Task ?/n (ETA ... seconds)`

Yeah this is makes more sense. Would need to change the callback API to parse and propagate this information https://github.com/yausername/youtubedl-android/blob/master/library/src/main/java/com/yausername/youtubedl_android/StreamProcessExtractor.java#L20

**Comment by xibr** [comment]
Ok I will implement it after I finish improving downloads tab.
