### ISSUE TITLE
finally it works

### ISSUE THREAD

**Issue by abelfn** [yausername/dvd#3]
v0.0.4 it works except it doesn't determine file size of videos for some sites.

**Comment by yausername** [comment]
Can you share such a link?
Most likely it is due to file size not being provided by youtube-dl.

**Comment by abelfn** [comment]
just try any video from this site
dailymotion
vimeo
pornhub
xvideos
xnxx
xhamster

**Comment by yausername** [comment]
File size is not provided by youtube-dl for these sites. 
Can't do much about it.
