### ISSUE TITLE
New version (0.1.3) does not work for Reddit videos

### ISSUE THREAD

**Issue by sbstn87** [yausername/dvd#34]
Hi, since updating to 0.1.3, version using yt-dlp, dvd does not work for reddit videos. Downgrading to 0.1.2 solves the issue.

**Comment by yausername** [comment]
reddit videos work fine for me on 0.1.3
Try updating yt-dlp from settings.
Maybe share a link to a video that doesnt work.

Thanks

**Comment by sbstn87** [comment]
yt-dlp is up to date.

Any link I try does not work, only the video is downloaded, there's no sound. Here's a screenshot of the app when I try to download a Reddit video:
![Screenshot_20220101-184204_dvd](https://user-images.githubusercontent.com/37237675/147856812-8967f740-1fa0-4685-8f4c-e369b02c74f7.png)

There's only one option and that's a highest quality video without sound.

When I downgrade to dvd 0.1.2, it looks like this for the same video:
![Screenshot_20220101-184538_dvd](https://user-images.githubusercontent.com/37237675/147856848-261a11d1-69c7-4c4c-ae68-d1ca973bbfbe.png)

**Comment by yausername** [comment]
It might be depending on the type of link. For example I see all options when I use these links

https://www.reddit.com/r/Minecraft/comments/bfvflz/after_not_playing_a_couple_years_i_bought/
https://v.redd.it/akvx01l3ipt21

But I only see DASH_1080 when i use
https://v.redd.it/akvx01l3ipt21/DASH_1080

**Comment by sbstn87** [comment]
Any chances to automatically removing the "/DASH_1080" or analogous part from the links shared to dvd?

**Comment by yausername** [comment]
I don't think that will happen. The link is passed to yt-dlp as is.
