### ISSUE TITLE
using download navi as download manager for dvd

### ISSUE THREAD

**Issue by ghost** [yausername/dvd#4]
can you use download navi
https://github.com/TachibanaGeneralLaboratories/download-navi
for the download manager.
It would be nice if you can.

**Comment by yausername** [comment]
Will look into it.

**Comment by abelfn** [comment]
i tryed it but the only problem i have to extract the url using youtubeDownloadRequest which takes a lot  (more than 30s) just to get the downloadable link and finally download it.

**Comment by xibr** [comment]
When using this, you must first verify that the video contains audio for YouTube. Not all links contain audio.

I'm using [adm](https://play.google.com/store/apps/details?id=com.dv.adm) but only for Instagram, Twitter and YouTube but for YouTube make check itag 22 or 18. 

you can do that for other sites.

**Comment by abelfn** [comment]
Thats what i did.Get m4a,webm,360p,720p but not 1080p since it downloads video and audio separetly requires merging which download navi not support not even made for such a kind of stuff.

**Comment by xibr** [comment]
The user deleted his account, and was replaced by a ghost.  Also I don't think implementing this is a good idea.
