### ISSUE TITLE
Simple browser

### ISSUE THREAD

**Issue by ghost** [yausername/dvd#5]
Simple webview browser, instead of copy and paste link or share link from other app.

1.replace home fragment with webview fragment.

2.add floating button on top of webview to download videos when playing or add context menu for webview with "Try download" to download videos directly  from home page(ex youtube.com).

3.change home fragment to activity, when user click download button or context "Try download" from webview it launchs FormatSelectorActivity, finally user selects his choice and download starts and close FormatSelectorActivity.while user downloading he can browse whatever he wants.
example vidmate or videoder

![vimeo](https://user-images.githubusercontent.com/63355586/84952628-ef38a180-b0fa-11ea-8a07-957bf53aa2b0.jpg)

**Comment by famo** [comment]
Strongly against this, bringing a browser to `dvd` brings a whole lot of privacy issues:
what about the cookies, the ads, the trackers...?

**Comment by xibr** [comment]
@yausername 
I don't think this will be implemented, closing?
