### ISSUE TITLE
How to download playlist?

### ISSUE THREAD

**Issue by DivineRose0** [yausername/dvd#50]
Is it possible to download playlists with this?

**Comment by yausername** [comment]
I tried this in the command mode and it seems to work. Make sure the target directory exists.
```
-o /sdcard/Download/youtubedl-android/%(title)s.%(ext)s -i -f mp4 --yes-playlist "https://www.youtube.com/watch?v=7Vy8970q0Xc&list=PLwJ2VKmefmxpUJEGB1ff6yUZ5Zd7Gegn2"
```

**Comment by DivineRose0** [comment]
Thanks, I'll give it a try and let you know how it goes.

**Comment by ICantInstall** [comment]
Is it possible to download the audio only too? 
I've tried this:
--extract-audio --audio-format mp3 -o /storage/emulated/0/dvd/%(title)s.%(ext)s --yes-playlist ""
and it said it did download something though it doesn't show up anywhere.

**Comment by xibr** [comment]
@ICantInstall 
`--extract-audio --audio-format mp3 -o /sdcard/Download/dvd/%(title)s.%(ext)s --yes-playlist "playlist url"`

**Comment by DivineRose0** [comment]
The command worked perfectly. Everything went to a dedicated folder in my download folder. However I can't seem to get it to extract audio only.......
