### ISSUE TITLE
Cannot install apk on my phone.

### ISSUE THREAD

**Issue by Djjscool** [yausername/dvd#54]
Whenever I try to install one of the APK's, it says "App not installed".

**Comment by MuhannadYT** [comment]
Try all the versions [here](https://github.com/yausername/dvd/releases/tag/0.1.4) , if non work then it's probably a storage issue

**Comment by xibr** [comment]
Is the problem solved?

**Comment by xibr** [comment]
No answer so I'm closing. Please feel free to open a new issue if you find another bug.
