### ISSUE TITLE
download progress notification does not update

### ISSUE THREAD

**Issue by wb1016** [yausername/dvd#56]
## system info
android 11, arm64, vayu

## expected behaviour
description of notification changes according to download progress

## what actually happened
![Screenshot_20220426-093057_GitHub~2.png](https://user-images.githubusercontent.com/47267045/165195816-9e4ebcfa-bf14-41f2-be2d-5c56e253b768.png)
notification freezes at download progress 0.1% even though download task is still ongoing and does not update untill download is complete

## how to reproduce
just download any twitch video

**Comment by Fehertukor** [comment]
Same problem I would love a fix.

**Comment by xibr** [comment]
Check the latest version https://github.com/yausername/dvd/releases/tag/0.1.5

**Comment by wb1016** [comment]
nice. it is working correctly now.
