### ISSUE TITLE
Feature request Audio download to mp3

### ISSUE THREAD

**Issue by Fehertukor** [yausername/dvd#58]
Hi!
I really like your app and thanks for it!
Would it be possible to add an option to download video files in  "only audio" version as mp3 file?
(Currently it is downloading them as mp4)

**Comment by jokezone** [comment]
The app already supports this feature on the yt-dlp commands tab. Granted, it would be more user friendly to add an mp3 download option on the video downloads tab.

**Comment by vinaykharayat** [comment]
> The app already supports this feature on the yt-dlp commands tab. Granted, it would be more user friendly to add an mp3 download option on the video downloads tab.

Agree need a more user friendly way to download mp3. Atleast making yt-dlp with some user friendly command execution.

**Comment by Fehertukor** [comment]
Solved with #seal thanks
