### ISSUE TITLE
[Suggestion] Share link to dvd.

### ISSUE THREAD

**Issue by Simber1** [yausername/dvd#64]
It would be cool if there was a share handler so you could share a link to dvd to open dvd with that link already searched for.

**Comment by maxfire2008** [comment]
I can already do this on my phone at least from YouTube. I'm on Android 11

**Comment by Simber1** [comment]
> I can already do this on my phone at least from YouTube. I'm on Android 11

You are correct, it is already possible. I could have sworn I looked and couldn't find it when I made the issue.
