### ISSUE TITLE
Using the --cookies command

### ISSUE THREAD

**Issue by worksbytk** [yausername/dvd#70]
I've been attempting to execute yt-dlp's --cookies command to access private/members-only videos but it doesn't work and I can't tell where it's failing.

I'm using a cookies.txt that works on my Windows machine and I've tried different phone directory prefixes and references to the file (like mnt/, file:///, and simply the root path) to no avail. Is it something I'm missing or does it not work?

**Comment by JunkFood02** [comment]
You can use the workaround I mentioned here. It's a problem about the storage permission of Android 10+

**Comment by worksbytk** [comment]
> You can use the workaround I mentioned here. It's a problem about the storage permission of Android 10+

Apologies for my lack of understanding, but I'm not quite sure I followed. I had the app make and use a new cookies.txt in which I copied my existing file's contents into, but that still didn't seem to work.

What did work was using Seal instead. Thanks for that!
