### ISSUE TITLE
Publish on F-Droid?

### ISSUE THREAD

**Issue by Pentaphon** [yausername/dvd#9]
As the title says. There's no Youtube-dl based tools on F-Droid and this would be good to add to there.

**Comment by 06000208** [comment]
Yeah, I came here to suggest this. The readme mentions that this app violates the play store's terms, but it would be fine on [F-Droid](https://www.f-droid.org/).

**Comment by IzzySoft** [comment]
@yausername [opened an issue](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6986) with F-Droid for inclusion, but must have missed all pings when asked for clarification. Without the issues fixed, it cannot be included there. So giving a last ping here before we have to close the RFP: could you please "come over" and answer the open questions, @yausername?

**Comment by yausername** [comment]
Hi @IzzySoft
I missed the pings over there.
I'll respond to the issues today.

**Comment by famo** [comment]
It is available on F-Droid now!

**Comment by Pentaphon** [comment]
> It is available on F-Droid now!

I see! Closing!
